name: Autocloser
on: [ issues ]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-close issues that did not follow issue template
        uses: roots/issue-closer@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "@${issue.user.login} This issue was automatically closed because you didn't use the template. Go here and try again: https://github.com/d8ahazard/sd_dreambooth_extension/issues/new/choose"
          issue-pattern: ".### Kindly read the entire form below and fill it out with the requested information."